# Generated by Django 4.0.5 on 2022-07-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_owner_comment_author_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='user', to='auctions.auction'),
        ),
    ]
