# Generated by Django 4.0.5 on 2022-07-17 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_user_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='date_modified',
        ),
    ]
