# Generated by Django 3.2.13 on 2022-07-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_auction_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='thereis_bid',
            field=models.BooleanField(default=False),
        ),
    ]
