# Generated by Django 4.0.5 on 2022-07-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_thereis_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
